### ISSUE TITLE
Bug: double values in indication

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#104]
Hey, 

i guess RKI changed the Excel again. There are double values in indication now.

**Comment by Rubber1Duck** [comment]
I can't see any changes by RKI! What do you meen?
Please provide a example!

**Comment by Akeel1994** [comment]
"indication":{"age":1239020.988,"job":1381553.278,

These values should be int values not double. There must have been a change in the excel like last time.

**Comment by Rubber1Duck** [comment]
Oh i belive i see what you meen:
![Indication](https://user-images.githubusercontent.com/6493772/108550845-64462180-72ef-11eb-83c5-0032c0b7c7f0.png)
![indication_excel](https://user-images.githubusercontent.com/6493772/108551414-37ded500-72f0-11eb-8156-b8fd2b8e4575.png)
I changed the format to make the dezimal point numbers visible!
 Because there are decimal point numbers in NRW in the original Excel Sheet, and the overal values are just the total of the states, the same dezimal point number is in the overall values!
I belive that will be corrected tomorrow, because dezimal numbers make no sence in indication values! 
The parser is working correctly!

**Comment by Akeel1994** [comment]
Exactly that's what I meant

**Comment by Rubber1Duck** [comment]
As i mentioned RKI corected this over the weekend!
I think this issue can be closed!
