### ISSUE TITLE
[Vaccination History] vaccinated and firstVaccination are the same

### ISSUE THREAD

**Issue by beyerleinf** [marlon360/rki-covid-api#110]
In the following line, `vaccinated` is set to `Erstimpfung` which basically makes this a duplicate of `firstVaccination`.
https://github.com/marlon360/rki-covid-api/blob/cf4abca0c0cf12b58d4ebe6f128c0ebafe3ef927/src/data-requests/vaccination.ts#L264

I think `vaccinated` should contain the sum of `Erstimpfung` and `Zweitimpfung`.

If you want me to make a PR, I can :)

**Comment by marlon360** [comment]
Hey @beyerleinf 

At the beginning of this API there was no distinction between the first and the second vaccination. That is why I just called it `vaccinated`.
Later on they split that into `Erstimpfung` and `Zweiimpfung`. In order to not break any current applications that rely on the `vaccinated` property I just left it there. 

If you need the sum use `administratedVaccinations`.
