### ISSUE TITLE
Feature Request: Get data by age

### ISSUE THREAD

**Issue by ChristophKrause** [marlon360/rki-covid-api#137]
The user wants to get the Inzidenz or Infection/death count by age group and landkreis.

For some age groups this seems to be delivered on
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0?selectedAttribute=Altersgruppe

Is it possible to implement the wrapper?

**Comment by lenaschimmel** [comment]
As far as I know, it's relatively easy to get the absolute case count by age group. I did this when I was working on [a project similar to rki-covid-data](https://github.com/lenaschimmel/covid-incidence-germany/blob/main/download.sh) 5 months ago, which I abandoned because rki-covid-data is much better (e.g. cleaner, faster).

I couldn't find the population data broken down by age groups, but just came across [risikogebiete_deutschland](https://github.com/semohr/risikogebiete_deutschland) which has that data as [csv](https://github.com/semohr/risikogebiete_deutschland/blob/master/assets/data/population_landkreise_altersgruppen.csv) and uses it to compute the incidence for each age group.
