### ISSUE TITLE
History incidence not correct

### ISSUE THREAD

**Issue by mindbreaker** [marlon360/rki-covid-api#148]
The history data of the weekly incidence is not correct:
![image](https://user-images.githubusercontent.com/225204/113483521-2dddf380-94a4-11eb-807f-ad6cd985f813.png)

Source: https://api.corona-zahlen.org/districts/09172/history/incidence/3

But if i compare it with the data of the district office, there is some differences.: 

![image](https://user-images.githubusercontent.com/225204/113483554-52d26680-94a4-11eb-8278-e59a69127b6e.png)

Greetings

**Comment by Rubber1Duck** [comment]
have a look at #64, please
Thats the same for incidence data! it behaves on all history data! the history isnt fix!
And it is a case of interpretation! the data witch is published 03.04.21 0:00 Uhr is the data from 2.4.2021! the API is "incorrectly" publisching 2021-04-02T00:00:00.000Z witch is a timestamp. the time 00:00:00.000Z you have to ignore! This i described here
[https://github.com/marlon360/rki-covid-api/issues/145#issuecomment-811436550](https://github.com/marlon360/rki-covid-api/issues/145#issuecomment-811436550)
And as you can see the date from the API and from the district office is for 2.4.2021 the same: 104,7871.... ~ 104,8. 
tomorrow it will be different because the cases that are published tomorrow are not all assigned to today (3.4.), some cases are assigned to 2.4 and maybe to different days in the past! the history data is dynamicly ...............

**Comment by mindbreaker** [comment]
Hi, 

ok. That simply means that here, for example, ten more cases were added later? That just seemed a bit high to me. I use the API to determine e.g. school openings or the emergency brake. But I don't know whether the current data is used and then simply archived, or whether the corrected data is used.

**Comment by SirRufo** [comment]
Well there is no history data for population but that is needed for calculating the real incidence value from history data.

https://github.com/marlon360/rki-covid-api/blob/3aea537f7a767ad3487efef4d81e53b75f1f99ae/src/responses/districts.ts#L197

**Comment by claaslange** [comment]
I understand that the RKI adds cases to old days and that lower incidences can result from a delay of notices to the RKI. However I see some discrepancies in the API and the offical Excel file that is provided by the RKI. Let's take Hildesheim as an example:

[This api call](https://api.corona-zahlen.org/districts/03254/history/incidence) returns the following incidences (just an excerpt):
```
[
...,
{
date: 2021-04-21T00:00:00.000Z,
weekIncidence: 112.03080303244543
},
{
date: 2021-04-22T00:00:00.000Z,
weekIncidence: 121.81990232654259
},
{
date: 2021-04-23T00:00:00.000Z,
weekIncidence: 118.1943099953955
},
{
date: 2021-04-24T00:00:00.000Z,
weekIncidence: 112.75592149867484
},
{
date: 2021-04-25T00:00:00.000Z,
weekIncidence: 116.01895459670723
},
{
date: 2021-04-26T00:00:00.000Z,
weekIncidence: 110.58056609998658
}
]
```

The [official excel file](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.html;jsessionid=1D86D8EFB208255BF6045D72596F8A4A.internet082?nn=13490888) lists the following incidences for Hildesheim (Row 168, Columns FB to FG):

* 21.04.: 90
* 22.04.: 91
* 23.04: 99
* 24.04.: 116
* 25.04.: 92
* 26.04: 110

The media and the districts themselves seem to look at the Excel file, when deciding on the new emergency brake law, as Hildesheim said they do not meet the 5 workdays above 100 AI/7. 

One example is Die Zeit. They say the access RKI data for this page as well: https://www.zeit.de/politik/deutschland/2021-04/corona-lockdown-notbremse-staedte-kreise-infektionsschutzgesetz-ausganssperre

Their numbers for Hildesheim seem to match the data from excel file better - although still not completely - than the data from api.corona-zahlen.org: 

<img width="705" alt="Bildschirmfoto 2021-04-27 um 11 50 35" src="https://user-images.githubusercontent.com/42106/116222407-deab7b80-a74e-11eb-96ce-cc6bd8976193.png">

Took a lot at the [json](https://hsr-cdn.zeit.de/corona/get/?query=query%20NotbremseOrNot%20%7B%0A%20%20kreise%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20notbremseActive_0%0A%20%20%20%20notbremseActive_1%0A%20%20%20%20notbremseActive_2%0A%20%20%20%20notbremseDatenstand%0A%20%20%20%20rkiIncidenceHistorical(limit%3A%2014)%20%7B%0A%20%20%20%20%20%20regionId%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20incidence%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A&operationName=NotbremseOrNot&variables=%7B%7D) the Zeit website loads. They also add data for "today", if you remove that, the data in there matches perfectly with the Excel File from RKI:

```
rkiIncidenceHistorical: [
{
__typename: rki_incidence,
date: 2021-04-27,
incidence: 110.6,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-26,
incidence: 109.9,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-25,
incidence: 92.1,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-24,
incidence: 116,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-23,
incidence: 98.6,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-22,
incidence: 90.6,
regionId: 3254
},
{
__typename: rki_incidence,
date: 2021-04-21,
incidence: 90.3,
regionId: 3254
},
```

Do you have any insights why the data differs? Or if there is potentially another source from the RKI?

**Comment by Rubber1Duck** [comment]
First of all, I have no idea with which background the RKI determines the incidence values ​​that are used to enforce federal laws!
If they speak from incidence values from today, they always meen the value from yesterday, because they are not able to calculate a incidence value from today, because today is running! they dont know how many cases are today, now! the cases are not updated until around midnight!
lets make a theoretical example to show different versions to calculate the incidence values
the virtual district have 150.000 residents!
following new cases are reported
23.04.2021     0 new cases
22.04.2021     21 new cases
21.04.2021     16 new cases
20.04.2021     0 new cases
19.04.2021     30 new cases
18.04.2021     15 new cases
17.04.2021     11 new cases
the calculated incidence value at 23.04.2021 is 62!
for 24.04.2021 the health department of our virtual district reports 35 new cases, but not all for 24.04.2021! 15 for 23.04.2021 und 20 for 24.04.2021.
now the table can look like this
24.04.2021     35 new cases   = 78 incidence
23.04.2021     0 new cases     = 62 incidence
22.04.2021     21 new cases
21.04.2021     16 new cases
20.04.2021     0 new cases
19.04.2021     30 new cases
18.04.2021     15 new cases
17.04.2021     11 new cases
this is what the excelsheet provide! But in my opinion this gives the districts room for manipulation! (just simply do not transmit a value every 2 days, and one incidence value will be unter a borderline, and simple report the cases one day later !!!!!!!!!!!)
or like this
24.04.2021     20 new cases = 78 incidence
23.04.2021     15 new cases now the incidence value for 23.04 is 72 !!!!!!!!!!!!!!!
22.04.2021     21 new cases
21.04.2021     16 new cases
20.04.2021     0 new cases
19.04.2021     30 new cases
18.04.2021     15 new cases
17.04.2021     11 new cases
 and that is the way this API calculates the incidence for history dates! there is NO way to calculate the historic incidence values witch are published every day from the database this API uses! because the historic values are not stored in the database and they are fully dynamicly, because of the late registrations for one or more days in the past.
If you want this values you have to store the actual value in a extra database every day (as the RKI do with the Excelsheet!).
The value for today (witch is the value for yesterday) in both versions are the same (normaly but if they repot cases for more than 7 days in the past the values differ!, but this is realy rare!)
As you can see here Hildesheim do so 
![Hildesheim](https://user-images.githubusercontent.com/6493772/116297394-82bb1400-a79b-11eb-882d-4382c730b379.png)
40 new cases are reported for 26.04., but only 23 for 26.04.!
![Hildesheim2](https://user-images.githubusercontent.com/6493772/116297906-1391ef80-a79c-11eb-87a8-720a12338aef.png)
11 new cases for 25.04. (bevor that are 0 !!!!! and that will bring down the incidence reported yesterday!) )
and
![Hildesheim3](https://user-images.githubusercontent.com/6493772/116298059-4b009c00-a79c-11eb-87c3-179d9383d1d9.png)
6 for 24.04.

so the "right" incidence values for 24.04. and 25.04. are higher than reported!

why they take the static values ............... i dont know

all Data for cases, deaths and recovered are taken from the Arcgis Database! 
[https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0)
and the incidence values are calculated from the new cases in this database.
till now i dont know this RKI excelsheet.

I hope i can bring some light in the darkness .....................

**Comment by claaslange** [comment]
Thanks for your long answer. It basically confirms what I was thinking. I just have no idea how anybody thinks, that it's the right thing to use the originally published data for any kind of decision 😅 

I'll take a deeper look at the Arcgis Database. As the graph in the dashboard is able to show "newly reported cases" maybe one could calculate the "originally reported cases" and use this to get to the incidences as they were reported initially.

**Comment by Rubber1Duck** [comment]
it is also possible to parse that excelfile and give that information with the other incidence values too.
maybe called p28bIfSGIncidence (for §28 b IfSG), unfortnatly the XLSX file have the dates in the column and not in the row, and i dont know if this is possible for ME to code this!? and @marlon360 seems very busy at the time.
Maybe anyone else is able with more experience in JS / TS as i have to code this!?

**Comment by PatrickHaussmann** [comment]
> it is also possible to parse that excelfile and give that information with the other incidence values too.
> maybe called p28bIfSGIncidence (for §28 b IfSG), unfortnatly the XLSX file have the dates in the column and not in the row, and i dont know if this is possible for ME to code this!? and @marlon360 seems very busy at the time.
> Maybe anyone else is able with more experience in JS / TS as i have to code this!?

@Rubber1Duck please have a look at #204

i am very willing to make the necessary pull request
