### ISSUE TITLE
RKI is Ratelimiting

### ISSUE THREAD

**Issue by antonstech** [marlon360/rki-covid-api#179]
When i am doing a request to the Germany Endpoint i get "Unable to perform query. Too many requests"
And not only on the public API even on my own docker Container :(

**Comment by antonstech** [comment]
Full Response:
`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":429,"message":"Unable to perform query. Too many requests.","details":["API calls quota exceeded (1512)! maximum allowed (1200) per Minute. Retry after 60 sec."]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

**Comment by derLoosi** [comment]
Heyho,

same problem here, tested both APIs (api.corona-zahlen.org and my own using docker) produces the error.

districts is working, but the endpoints germany and states are limited since today (or has always been but the limit never got exeeded before).

Endpoint States:
`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":429,"message":"Unable to perform query. Too many requests.","details":["API calls quota exceeded (2011)! maximum allowed (1200) per Minute. Retry after 60 sec."]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

Endpoint Germany:
`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":429,"message":"Unable to perform query. Too many requests.","details":["API calls quota exceeded (1619)! maximum allowed (1200) per Minute. Retry after 60 sec."]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

**Comment by JonathanN1203** [comment]
same issue like https://github.com/marlon360/rki-covid-api/issues/175

**Comment by Rubber1Duck** [comment]
and as written, this is not a issue off this API! 
It seems that many people are using the RKI API (and not only with **this** API and all the local clones, manny have build thier own "API" or will pull the data directly from the RKI API in their applications to meet thier specs) in the meenwhile, unfortnatly all in the morning to get fresh data. so i think the accesses to the RKI API increases dramaticly. yesterday all was running in the afternoon again.

**Comment by mmkk19** [comment]
Would it be possible to rebuild this API such that at least the old cached data is delivered?
The server status could be returned as a separate JSON object.

This would mitigate the impact on the applications.

**Comment by Rubber1Duck** [comment]
There is neerly nothing what is not possible :-)
this meens that the data must be stored localy. in the past Marlon wouldn'd do that. And maybe that will not solving the issue, because of many other requests to the RKI API (i think).
and i'm afraid @marlon360 has no time for this, because he is busy. I cant do that (my TS experience is not good enough).

Everyone feel free to write a PR!

**Comment by mmkk19** [comment]
I thought there was already a cache? Let's just return what is in it in case of an RKI error instead of passing that error to the API consumers?

I am not a web dev expert either, so maybe I have missed a point, but I would appreciate if someone would take the time to evaluate this approach.

And no, this would not solve the original, stupid issue (1200 requests a minute? Isn't that close to nothing?) but if let's say the data can be retrieved already at 5 am we would have that available until the next update opportunity.

**Comment by Toni-99** [comment]
The problem is, that the rki is transmitting some new cases over the day. But yeah, i think its the best way to cache it. Does someone has a workaround? Its affecting all of my Services and that of many others too :o

**Comment by matze1708** [comment]
I think there are several possibilities. 

First, you could store the data in a database, but it is expensive.

Or you use something like a store, where the data is stored. Then you should look at the request first, whether the data are already in the store, then you get these data or whether these are not yet daily updated, then these are retrieved from the RKI.

Also possible would be this event or time controlled.

**Comment by matze1708** [comment]
What about this:?
[https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.cache.html](url)

**Comment by Rubber1Duck** [comment]
> 
> 
> The problem is, that the rki is transmitting some new cases over the day. But yeah, i think its the best way to cache it. Does someone has a workaround? Its affecting all of my Services and that of many others too :o

Do you have a example that the once updated Data will update again on the same day? haven't seen this for cases, death, and recovered. maybe this will be done in the used xlsx sheets, but actually I don't think so. they have more to do as of transmitting some new or updated cases over the day...... (just my 2 cent) 

By the way, the data in this API is already cached for 1800 seconds with redis-cache

**Comment by p-tenz** [comment]
I have currently the problem when querying the 
[History Data of a district](https://api.corona-zahlen.org/districts/08119/history/incidence/3):
Getting this error, while **iot.shinewelt.de** is not my URL. I am querying from a wordpress plugin.
```
error |  
-- | --
message | "There is a problem with the official RKI API."
rkiError |  
code | 429
message | "Unable to perform query. Too many requests."
details |  
0 | "API calls quota exceeded (1237)! maximum allowed (1200) per Minute. Retry after 60 sec."
url | "https://**iot.shinewelt.de**/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,0) AND IdLandkreis = '08119' AND MeldeDatum >= TIMESTAMP '2021-04-06'&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,Landkreis,IdLandkreis&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis,MeldeDatum&groupByFieldsForStatistics=IdLandkreis,MeldeDatum,Landkreis&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="
```
