### ISSUE TITLE
frozen incidence history

### ISSUE THREAD

**Issue by PatrickHaussmann** [marlon360/rki-covid-api#204]
rki publishes the frozen incidence values in an excel file. This file is also used for the "emergency brake" (Notbremse).  Please look here [rki.de/inzidenzen](https://rki.de/inzidenzen).
i have written a new file in the data-requests folder. this change would fix #148 
Please take a look: [incidence.ts](https://github.com/PatrickHaussmann/rki-covid-api/blob/7a602774781237c1991bac3a83fbe3493fa0d0c8/src/data-requests/incidence.ts)

i am very happy to write a pull request, i just need help to structure the changes and split them into the necessary files and functions.

I would also find it very helpful to return the status of the emergency brake for each district as suggested in the linked file, as it is relatively complicated to calculate.

**Comment by Rubber1Duck** [comment]
in my opinion, it is a realy good idea to implement this "frozen" incidences. My first idea was to wrote this frozen incidences direktly under all existing "dynamicly" incidences (federal, states, districts and their historys), and name they ass descibed in #148. But maybe this is not a good idea to change existing json structures, because that will bring much work to all the existing API users, to update their apps!
To prevent that, that must be a new endpoint, i think.
I'm unsure if returning the status of the emergency brake should be a part of this API, because this API is defined as:
"A JSON Rest API to query all relevant corona data for Germany based on the figures of the Robert Koch-Institut."
and the status of the emergency brake is not data from the RKI, the RKI is providing the values, and what politics makes of it is a matter for the federal and/or state governments. Publishing this status with this API will bring mucht discussions e.g. your status wrote all stores are open in my district, but they are closed,  and so on. 
If a app programmer wants to provide this information he/she/it should analyse this data by him/her/itself.
And in the past Marlon has always made sure that only data from the RKI is published!
just my 2 cents ....................

**Comment by PatrickHaussmann** [comment]
it makes incredible sense to me not to build the emergency brake status into this api. thanks for this feedback
the idea with the emergency brake was just a try. see it as a possibility how to use this data or why i think this are useful


do i understand correctly that you would name these endpoints like this?
/districts/history/p28bIfSGIncidence
/districts/:ags/history/p28bIfSGIncidence
my slight criticism would be that the names of these endpoints are not easy to remember. But which name the frozen incidence values get in this project is not important to me.

**Comment by Rubber1Duck** [comment]
> do i understand correctly that you would name these endpoints like this?
> /districts/history/p28bIfSGIncidence
> /districts/:ags/history/p28bIfSGIncidence
> my slight criticism would be that the names of these endpoints are not easy to remember.

you are right thats my idea, but you are also right that is not easy to remember .......... but it should be clear that these incidence values ​​are different from the others. maybe "ebrakeincidence" for the endpoints and "eBrakeWeekIncidence" for the JSON list are better names!?

Any other ideas for that names from you or others?

Keep the documentation in mind when you do the PR

**Comment by Rubber1Duck** [comment]
Another hint from me,
the district numbers (ags) in the XLSX File are without a leading zero if they are only 4 digits long e.g. 1001 and not 01001. But all the other district numbers that came out of the ArcGis Database are alsways 5 digits long and i think it is a good idea to keep this for the :ags value in the endpoint and for the header in the json list!

**Comment by marlon360** [comment]
Great idea @PatrickHaussmann! 
And good points from @Rubber1Duck.

To conclude:
- we should only offer the raw RKI data, which means that "emergency break" thresholds should not be included
- `ags` should have the same format throughout the API, which means we need the leading zero
- "frozen incidence" and "updated incidence" should have different endpoints

The last open question is how we are going to name the endpoints.
I think it could make sense to use `https://api.corona-zahlen.org/districts/history/incidence` for the frozen incidence, because there was a lot of confusion around the calculation of the values. And in most cases the frozen incidence is what the people want to work with. What do you think @Rubber1Duck and @PatrickHaussmann?

The updated incidence could be available under `https://api.corona-zahlen.org/districts/history/updated-incidence`.

**Comment by Rubber1Duck** [comment]
> I think it could make sense to use `https://api.corona-zahlen.org/districts/history/incidence` for the frozen incidence, because there was a lot of confusion around the calculation of the values. And in most cases the frozen incidence is what the people want to work with. What do you think @Rubber1Duck and @PatrickHaussmann?
> 
> The updated incidence could be available under `https://api.corona-zahlen.org/districts/history/updated-incidence`.

For me that sounds like a good idea, but what is about all the other incidences for states and whole germany? if the districts incidence is changing to the "frozen" incidences in the old endpoint from today to tomorrow also the states and germany incidence and thier history should change, so for states and germany there are also new endpoints needed for the (old)updated-incidences (i dont whant to miss that values) to be on a clear line!
So that ends up in much more work as only one new endpoint with the new data that most people want to see. it is not necessary to make new endpoints for states and for germany today, because at the moment, no political decision depends on it as i know.
The more I think about it, it may not be a bad idea to write the frozen value behind (or bevor) each existing "old" incidence value that is now used.
e.g.
date:                     2021-04-21
frozenIncidence:    135.4
updatedIncidence: 145.2
(The names are only examples!)

it looks like it is not an easy decision, everything has its advantages and disadvantages.
The easiest way is to make a new endpoint for new data i think. anyone who wants to use the new values ​​can do it, all others don't!
(oh man ihr verlangt mir hier in meinem alter ganz schön viel englisch ab ....... :-) ich hoffe es ist alles verständlich wie ich es meine.....)

**Comment by PatrickHaussmann** [comment]
i'm not a fan of changing the api structure. that's why i'm against adding the frozen values to "/districts/history/incidence" or even replacing it. besides, rubber1duck rightly said that it becomes inconsistent for incidences for states and whole germany.

I would argue for something like this:
/districts/history/frozen-incidence
or 
/districts/history/frozenIncidence
or something similar 

> And in most cases the frozen incidence is what the people want to work with

yes that is correct but i would expect /districts/history/incidence to return the incidence values of the last x days. the frozenIncidence values however are **not** like that, they are not updated even though it is clear that the rki does not have enough data on the day itself (as seen in the past) to calculate an accurate value. 

thats why a think it should be a new endpoint

leading zeros for ags is not a problem

**Comment by marlon360** [comment]
Okay let's go with `/districts/history/frozen-incidence` and keep the endpoints as they are right now.

**Comment by Rubber1Duck** [comment]
this is a good decision and i'm looking forward to the result
