### ISSUE TITLE
Vaccination delta calculation

### ISSUE THREAD

**Issue by tim-seidel** [marlon360/rki-covid-api#218]
Hi,

first of all: thanks for this nice API :)

I noticed something with the vaccination delta calculations: If you look at the vaccacination history (vaccinations/history) data you get for a single day (e. g. 06.05.2021):

```
{
   "date":"2021-05-06T00:00:00.000Z",
   "vaccinated":733366,
   "firstVaccination":733366,
    "secondVaccination":199129
}
```

Currently there is vaccinated = firstVaccination.
Shouldn't the value of vaccinated be: vaccinated = firstVaccination + secondVaccination?

(This vaccinated value is also used in the /vaccinations API as the current delta).

If you add those first firstVaccination + secondVaccination data it would match exactly with the data from https://impfdashboard.de/

**Comment by Rubber1Duck** [comment]
Hi,
that the vaccinated value is the same as the firstVaccination Value is for compability reasons! (so that the app Users dont have to change there programs! the vaccinated value is the first and only value that is published in the past when vaccination beginns.
to have the total of vaccinatins you have to calculate that in your app yourself, or take the admisteredVaccination from the /vaccinations endpoint. 
Thats a known bug or call it feature whatever, ......... whether that is still necessary ... no idea but thats the reason!

**Comment by tim-seidel** [comment]
Ye, I was looking why the delta in the /vaccinations endpoint was a little off to the data of other websites and then saw that the source of this delta to yesterday is the calculation in the history as described above. 

I will now retreive the delta to yesterday by using 

`/vaccinations/history -> history[latest].firstVaccination  + history[latest].secondVaccination `

instead of

`/vaccinations -> delta`
That should seel the deal ;)
