### ISSUE TITLE
4 days r value missing

### ISSUE THREAD

**Issue by davidkokoschka** [marlon360/rki-covid-api#256]
The "value" field in 4 days r value is missing. It only shows "date" field:

`"r":{"rValue4Days":{"date":"2021-07-16T00:00:00.000Z"},"rValue7Days":{"value":1.25,"date":"2021-07-15T00:00:00.000Z"},`

Could anybody fix it?

**Comment by JonathanN1203** [comment]
which url do you use?

**Comment by davidkokoschka** [comment]
https://api.corona-zahlen.org/germany

**Comment by DanielMensch** [comment]
Also the "value" directly below "r" is missing. At least it is mentioned in the example response here: https://api.corona-zahlen.org/docs/endpoints/germany.html#response

Because of that one missing, it breaks the API.

I guess, it´s bc the rValues of the last entry here is missing: 

https://raw.githubusercontent.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/main/Nowcast_R_aktuell.csv

![image](https://user-images.githubusercontent.com/58559446/126636549-99045391-05b6-49af-a29f-60f33b6bf3f2.png)

**Comment by Rubber1Duck** [comment]
![r-wert](https://user-images.githubusercontent.com/6493772/126804499-21c98ed1-1ec8-43a2-b498-62bb0e9d1270.png)

es wäre möglich den 4-Tage r-Wert zu berechnen. aber diese API gibt nur Zahlen weiter die vom RKI veröffentlicht werden!

Alle die das in ihrer APP machen wollen
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/R-Beispielrechnung.xlsx?__blob=publicationFile

Ich schlage vor die werte von r: und rValue4Days: auf null zu setzen.

it is possible to calculate that 4-day r-value, but this API is only providing values the RKI is publishing.

for all of you who want to calculate that value in thier app see 
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/R-Beispielrechnung.xlsx?__blob=publicationFile  

i suggest to set r: and rValue4Days: to null

**Comment by Rubber1Duck** [comment]
PR is written, hopefully @marlon360  will merge this soon .....

**Comment by Rubber1Duck** [comment]
I decided to write a alternative. @marlon360 has to decide witch one he will merge.
