### ISSUE TITLE
Idea: New map colours

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#323]
Hi, due to the increasing numbers and because this is unlikely to end, I wanted to ask about expanding the colour legend for /maps. Currently the colour legend ends at >1,000 and this is what many south/east counties will be exceeding the days. For the same reason, the major media have also adjusted their legends. Accordingly, grey is not 0 - 1, but more than 1,000. 
I would find it nice if the legend could be extended upwards by one or two, as it would be easier to distinguish the values. Accordingly, I have the following suggestions: 

0-1   25BA94
1-15   76D985
15-25   FFFFA8
25-35   FECA81
35-50   F1894A
50-100   F21620
100-200   A9141A
200-350   B275DD
350-500   5D179B
500-1.000   563B3E
1.000-1.500   000000
1.500-2.500   646464
> higher than 2.500   FFFFFF           | I know this value is high, but one could still incorporate it. 

I would be happy if the legend could be expanded in this respect. Of course you can also write your opinion here. 

![image](https://user-images.githubusercontent.com/63804808/141158338-1bdec81a-f7aa-450f-8293-58d8f87bcfda.png)

**Comment by Rubber1Duck** [comment]
that should not be a big deal ................ 
@marlon360 do you have any objections with this?

**Comment by Rubber1Duck** [comment]
in my opinion black should be the last color und we should not use white ........... maybe like this
![newmap](https://user-images.githubusercontent.com/6493772/141172897-a9c08a63-485e-47ce-bf5d-cb0c33be5920.png)

**Comment by HappyFr1tz** [comment]
What is your opinion to that? Here the colours are rather adapted to each other. Because I think your two shades of grey are very difficult to distinguish. 
![image](https://user-images.githubusercontent.com/63804808/141174101-28f00fb8-5c77-445e-bfdc-93111824d9c3.png)

**Comment by Rubber1Duck** [comment]
thats okay for me! the hex values please ..... :-)

**Comment by HappyFr1tz** [comment]
0-1 25BA94
1-15 76D985
15-25 FFFFA8
25-35 FECA81
35-50 F1894A
50-100 F21620
100-200 A9141A
200-350 B275DD
350-500 5D179B
500-1.000 17179B
1.000-1.500 543D35
1.500-2.500 5C5C5C
higher than 2.500 000000

**Comment by HappyFr1tz** [comment]
@Rubber1Duck are you writing a pull request?

**Comment by Rubber1Duck** [comment]
yes i am on the way.  But since not everyone will be happy when the maps change, there will be an option with which the colormap can be selected! e.g. /map/districts/:colormap or /map/districts-legend/:colormap 
without parameter the old colormap will be used!
change will comming soon ..... give me some time and first another PR must be accepted

**Comment by marlon360** [comment]
The RKI uses gray for districts that have an incidence of `0`. Because `0` mostly indicates a reporting problem.
Maybe we should add a light gray for exactly `0` and after that we can start with green for `>0`.

![Bildschirmfoto 2021-11-10 um 22 20 10](https://user-images.githubusercontent.com/11810704/141195196-f62a3d8d-ad11-4f39-a770-9ff5dafcd7c2.png)

@HappyFr1tz I like your legend!

@Rubber1Duck Do you think that people need the option to choose a colormap?

**Comment by HappyFr1tz** [comment]
I also like the suggestion to start with light grey for exactly 0.0 and then we continue with green. But do we want to continue to take gray for one of the high values or rather a dark blue or for 0.0 a white and for high values still the gray? 
To the suggestion, where you can choose the colors yourself. I like it when you can then decide between a few palettes or even select all colors, but such a function would still have a bit of time in my opinion, because for example I, in my project, was contacted several times today that the legend should be extended.

Edit
Regarding the selection of colors. At the moment, we cannot choose the colors ourselves, as they are also defined here and would only expand them now.

**Comment by Rubber1Duck** [comment]
> 
> @Rubber1Duck Do you think that people need the option to choose a colormap?

I thought that maybe not all users of the api advocate an extension of the ranges including changed colors. Maybe they have self made legends in their apps or whatever. And it is not a problem to provide switchable palettes, it is almost ready :-) in my brain :-)

**Comment by Rubber1Duck** [comment]
@marlon360 have a look on branch extend_ranges
The docs are not changed yet!

**Comment by HappyFr1tz** [comment]
> > @Rubber1Duck Do you think that people need the option to choose a colormap?
> 
> I thought that maybe not all users of the api advocate an extension of the ranges including changed colors. Maybe they have self made legends in their apps or whatever. And it is not a problem to provide switchable palettes, it is almost ready :-) in my brain :-)

I also used my own legend, which I have automated in the margin. It is not a big effort to edit the legend now. Recently, for example, the colour for 0-1 was changed and everyone implemented it without complaining. One could also continue to offer the current legend and add an extended one to 2,500. Then instead of the current two maps with two graphics each, there would be four graphics. But this is just an idea of mine, because I can't estimate how long you need to implement the different colour palettes.

**Comment by Rubber1Duck** [comment]
Hello, it is ready, need the final colors and the docs have to be enhanced for the new feature  and then it can go live! In my opinion,  dont know marlons one

Am 11.11.2021 15:15 schrieb HappyFr1tz ***@***.***>:
I also used my own legend, which I have automated in the margin. It is not a big effort to edit the legend now. Recently, for example, the colour for 0-1 was changed and everyone implemented it without complaining. One could also continue to offer the current legend and add an extended one to 2,500. Then instead of the current two maps with two graphics each, there would be four graphics. But this is just an idea of mine, because I can't estimate how long you need to implement the different colour palettes.

**Comment by HappyFr1tz** [comment]
How many colors do you need, @Rubber1Duck ? 
Then you could still make suggestions so that @marlon360 only has to change a little bit so that it can go online.

**Comment by Rubber1Duck** [comment]
I will have the PR ready today in evening, latest tomorow in the morning (now i have to look soccer :-) ).
i have made the light gray for incidences  that 0 and chose a drak brown for the other gray that is presenting the higher incidences. made also a palette that is like the one on the RKI website
it looks good for me. I am looking forward that it will go live tomorrow ....................
after this i will make a solution that the user kann selfconfigure the ranges and colors ..........
so please be patient until tomorrow

**Comment by marlon360** [comment]
I merged #318. I also added the option to define a range, that has to exactly match a value (for the 0 incidence range)
Now someone can make a PR with updated colors.
