### ISSUE TITLE
R-Value: Wrong values

### ISSUE THREAD

**Issue by nohn** [marlon360/rki-covid-api#331]
The RKI data source https://raw.githubusercontent.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/main/Nowcast_R_aktuell.csv contains PS_7_Tage_R_Wert ("Punktschätzer", "Point estimates"), UG_PI_7_Tage_R_Wert ("Untergrenze 95%", Lower boundary 95%), and OG_PI_7_Tage_R_Wert ("Obergrenze", Lower boundary 95%) while the API lists them as value, 7day value and 4day value which is IMHO not correct.

**Comment by Rubber1Duck** [comment]
Hello,
in TV, Radio and all other medias the PS Value is published, mostly one one value for the R-value! nearly all graphics with a curve from the r-value uses the PS value, not a range ...........
What would you prefer? all three values? but then we have a problem with the 4 day value, because the rki is not providing this value since a few weeks. What this api is providing as 4-day value is self computed, thats not realy difficult, but the upper and lower 95% values a harder to calculate!
If you know a way how the upper and lower 95% cvalues are calculated ............. it is not a big deal to implement that also the upper und lower values are provided by this api too ......

**Comment by nohn** [comment]
OK, so then please help me understand:

- r.rValue7Days.value is the RKI PS value?
- r.rValue4Days.value is calculated internally
- what is r.value? Currently it matches r.rValue4Days.value but is that always the case? My impression in the last days (but I haven't recorded the values) is that it represented one of OG/UG. I would expect r.value to be r.rValue7Days.value (PS), because that's what's communicated everywhere.

**Comment by Rubber1Duck** [comment]
> 
> 
> OK, so then please help me understand:
> 
>     * r.rValue7Days.value is the RKI PS value?
yes thats right!

> 
>     * r.rValue4Days.value is calculated internally
also right

> 
>     * what is r.value? Currently it matches r.rValue4Days.value but is that always the case? My impression in the last days (but I haven't recorded the values) is that it represented one of OG/UG. I would expect r.value to be r.rValue7Days.value (PS), because that's what's communicated everywhere.
 
that r.value is always a copy of r.rValue4Days and is shown for legacy reason. the 4 and 7 days values are not provided by this api from the beginning of providing the r value. At the beginning of providing this r-value it was the 4-day r value. at this time the 4 day r-value is provided by rki also! and to not breaking all the Endusers apps it is also outputted!

**Comment by Rubber1Duck** [comment]
@nohn do you think this issue can be closed? or do you have any further questions?
