### ISSUE TITLE
Deaths and new infections wrong

### ISSUE THREAD

**Issue by foaryon** [marlon360/rki-covid-api#479]
Hello,

the number of new infections is wrong or slowly updated and the numbers of deaths per week for states is also wrong.

**Comment by foaryon** [comment]
R Wert also wrong

**Comment by Rubber1Duck** [comment]
Witch endpoint?
/germany? States? Districts?
More info is verdammt helpfull

**Comment by Rubber1Duck** [comment]
I am on vaccation at the moment, and have limited resourses to internet and Not the right Equipment to check this all the way...
But at a  Quick check of /germany against the rki dashboard icant See wrong values!
Also the r-value  for /germany and the value in the official Excel file are equal!
I cant See any issues here!
Please decribe your issue in more Detail, maybe with screenshots!
Thank you

**Comment by foaryon** [comment]
Endpoint: states

deaths per week are wrong: sum shows 156 overall but its not..

![image](https://user-images.githubusercontent.com/20794218/197301417-3ca70418-e6c7-402f-87c9-dec9e98d4c20.png)

Don't know why it soo low in numbers. We had 178 deaths just today....Why its weekly 156 combined over all states??!

**Comment by Rubber1Duck** [comment]
Hi [foaryon](https://github.com/foaryon)
Thats because not all 178 people died yesterday! if one or more are died bevor (yesterday minus 7 days: today this is 2022-10-15) you dont see this in the deaths per week! this value is total dynamic! this is only valid for today (btw. yesterday)
thats the case for cases and recovered also!
feel free to ask more questions if something is not clear for you! if i find some time in my vaccation i will answer as soon as possible.
if you are german you can do this in german too, maybe thats makes all a little bit more clear!
If you dont have any questions about this, may i ask you to close this issue?

**Comment by Rubber1Duck** [comment]
no more questions.... closing
