### ISSUE TITLE
German history data not matching for week incidence?

### ISSUE THREAD

**Issue by MacSass** [marlon360/rki-covid-api#515]
Hi,
I liked to use the API and it worked fine in the past to show up to date week incidence as well as a graph of the last 28 days.
Lately the history data for week-incidence does not seem to match the data that I get on daily basis. The historic week incidence seems to be way too low.

E.g. for 6.4.2023 - the call of https://api.corona-zahlen.org/germany/history/incidence/28 gives me 
{"weekIncidence":9.87960612382523,"date":"2023-04-06T00:00:00.000Z"}
while the week incidence reported by RKI for that day is 21:
![image](https://user-images.githubusercontent.com/25532047/230800392-2d3960b2-5833-4dcf-a5fd-1a020c218732.png)

Also the weekIncidence for today (10.4.2023) reported by the API is 
{"cases":38368891,"deaths":171411,"recovered":38118122,**"weekIncidence":15.684107490306848**,"casesPer100k", so considerably higher than what the history data reports for even 4 days ago ...

In the past I had matching values for week incidence for the day and historic data ... what am I missing?

Thanks - MacSass

**Comment by Rubber1Duck** [comment]
Hi MacSass, thanks for submitting this issue.
End of february 2023 the RKI stopped some API's, where this API is pulling his data, so we had to look for other data sources. Most of the data this API is using now, are calculated from the dalily published dumps. We did not take into account that the population of Germany is determined differently and were therefore doubled for Germany. As a result, the values ​​of the incidence history were calculated only half as large.
This will be fixed with a PR i just wrote.
But this is only one part of the different values!
If you want to see history values of the incidence the RKI had reported on THAT days you have to take the "frozen-incidence" history!
https://api.corona-zahlen.org/germany/history/frozen-incidence/7
![2023-04-10 05_42_20-Window](https://user-images.githubusercontent.com/6493772/230834594-beeeef63-5a7c-4d51-9426-908f5433065c.png)
as you can see here for 2023-04-06 the value is 20.95...... rounded up to 1 digit it is 21.0
but attention! here the date is the reporting date! witch meens: this value is reported at day x, and that is the value for day x-1
these values are static! ( all today reported values are the values from yesterday!)

this is differend to /germany/history/incidence/7 (after Marlon reviewed and merged the PR!)
![2023-04-10 05_53_36-Window](https://user-images.githubusercontent.com/6493772/230836662-a7cb7d27-bcd7-440e-a4d1-bf7c79e14eb4.png)
here you have to interpret the date as: this is the value on date x! (thats the same as for cases, deaths and recovered history!)
as you can see the value is round about 1 higher than the frozen incidence value! due to late registrations for this day (and for possibly earlier days) the value for this day has increased!
This values are dynamicly! maybe tomorow you will see slightly differend values for each day!

The different interpreting of the date values are disscussed many times on months befor, but unfortunately no agreement could be reached here for a long time! It looks as if all users of this API have now come to terms with it and take the values ​​into account accordingly in their applications.

**Comment by MacSass** [comment]
Thank you @Rubber1Duck for the detailed and clear explanation.
I will happily use the /germany/history/incidence/X end-point then after your PR - in the mean time I will just double the values for my current dashboard, until PR has happened.
Thanks again for your effort - MacSass
