### ISSUE TITLE
Map with specific date

### ISSUE THREAD

**Issue by marlon360** [marlon360/rki-covid-api#56]
I would also love to have a parameter for the maps, to see the map of a specific date.

_Originally posted by @CodeBrauer in https://github.com/marlon360/rki-covid-api/issues/51#issuecomment-753542673_

**Comment by Rubber1Duck** [comment]
working on that issue, but first i have to solve #82 because i need that data to be correct!

How do the input look like?
/map/districts/history/:days e.g. /map/districts/78 to go 78 days in the past
or
/map/districts/history/:date e.g. /map/districts/2020-12-24 (or 24-12-2020 or the american format 12-24-2020) to show the districts map from 24.12.2020 ?

or should all be supportet?

my favorits are days and date in format 2020-12-24 (i think this is called the ISO Format?!)

all that the same for states!

What do you all think?

Comments are very welcome ................

**Comment by CodeBrauer** [comment]
@Rubber1Duck A static date format `YYYY-MM-DD` (ISO_8601) would be better. The data stays the same if you share the url / call it days later. If anyone wants to go 78 days in the past, he can just calculate the date.

**Comment by Rubber1Duck** [comment]
Thanks for your comment.
I would prefer that also, but in order to stay in the history form that has been used so far, the :days variant must also be included, and i dont know at the moment if i'm able to code that (both formats) but we will see.
Still working on it!

**Comment by Rubber1Duck** [comment]
At this time we have to discuss witch incidence values shound be taken for that maps!
that cracy frozen-incidence values witch are taken for political descissions, or the dynamicly "real" incidence values witch are for the past mostly higher?
