### ISSUE TITLE
Miscalculated history?

### ISSUE THREAD

**Issue by xrstf** [marlon360/rki-covid-api#64]
I am fetching the stats for district 02000 (Hamburg) on a daily basis. This so far gave me these numbers for _cases_:

* 2021-01-10: 40,476
* 2021-01-11: 40,687 (+211)
* 2021-01-12: 40,960 (+273)
* 2021-01-13: 41,350 (+390)

When I now request the history for the district, it tells me

```json
{
  "cases": 287,
  "date": "2021-01-10T00:00:00.000Z"
},
{
  "cases": 309,
  "date": "2021-01-11T00:00:00.000Z"
},
{
  "cases": 26,
  "date": "2021-01-12T00:00:00.000Z"
}
```

None of this fits together, I am probably not understanding the history. Can you explain it?

**Comment by marlon360** [comment]
Hello @xrstf!

The history gets updated by RKI everyday, because not all data is available at the corresponding day.
So it often happens that the health department reports cases that they registered a few days ago, so the RKI has to update the history.

What the media calls "Neuinfektionen" are not the new cases in the last 24 hours. They are just the cases that got reported by the health departments the last day.

> In Deutschland übermitteln die rund 400 Gesundheitsämter mindestens einmal täglich (in der aktuellen Lage noch häufiger) pseudonymisierte Daten zu bestätigten COVID-19-Fällen auf Grundlage des Infektionsschutzgesetzes elektronisch an die Bundesländer. Die wiederum übermitteln die Daten zu den COVID-19-Fällen elektronisch an das RKI. Für die Berichterstattung wird seit 18.03.2020 täglich der Datenstand 00:00 Uhr verwendet.
Zwischen dem Bekanntwerden eines Falls vor Ort, der Meldung an das Gesundheitsamt, der Eingabe der Daten in die Software, der Übermittlung an die zuständige Landesbehörde und von dort an das RKI liegt eine gewisse Zeitspanne. Die kann gemäß den Vorgaben im Infektionsschutzgesetz zwei bis drei Arbeitstage lang sein. In der aktuellen Lage erfolgt die Übermittlung deutlich schneller als im Routinebetrieb, weil Daten schneller verarbeitet werden. Dass einige Fälle mit etwas Verzögerung im Gesundheitsamt elektronisch erfasst werden, liegt auch daran, dass die Gesundheitsämter zunächst Ermittlungen zu den einzelnen Fällen und deren Kontaktpersonen durchführen und prioritär Infektionsschutzmaßnahmen ergreifen müssen, was die Ressourcen der Gesundheitsämter bereits stark in Anspruch nimmt. Ebenso werden die Daten am RKI validiert, um verlässliche Daten zu veröffentlichen. Auch innerhalb dieses Prozesses kann es zu geringen Verzögerungen kommen.

So if you collect the cases everyday in a database you will get much higher numbers compared to the actual cases at this day.

**Comment by xrstf** [comment]
Thanks for the help :-)

**Comment by marlon360** [comment]
There is now a new endpoint for incidence values that are not updated over time:
https://api.corona-zahlen.org/districts/history/frozen-incidence

**Comment by VocalZero** [comment]
@marlon360  Would it be possible to include the whole thing for general statistics (/germany) or states statistics as well?
Example: https://api.corona-zahlen.org/germany/history/frozen-incidence or https://api.corona-zahlen.org/states/history/frozen-incidence

**Comment by HappyFr1tz** [comment]
@Rubber1Duck @marlon360
